# Generated by Django 4.2.24 on 2025-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart_order_cartitem_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('open_hours', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
